# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

jobs:
  docs-build:
    docker:
      - image: node:17.2.0
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}   
      - run:
          name: Install and configure
          command: sudo -u node npm install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths: 
            - node_modules  
      - run:
          name: Generate website
          command: sudo -u node npm run-script build
      - run:
          name: Update Linux libs
          command: apt-get update
      - run:
          name: Install sudo
          command: apt-get install -y sudo
      - run:
          name: install dependencies used by pdf generator
          command: apt-get install -y libxshmfence1 libnss3-dev libgdk-pixbuf2.0-dev libgtk-3-dev libxss-dev libasound2
      - run:
          name: Generate PDF
          command: sudo -u node npm run-script pdf-build #sudo -u node npm run-script pdf-build
      - persist_to_workspace: #save the _site folder for the next job to run(./_site), the folder generated by eleventy with all the html in it
          root: .
          paths: _site
  docs-deploy:
    docker:
      - image: node:17.2.0
    steps:
      - checkout
      - attach_workspace: #get the saved folder(./_site) in this job so we can use it
          at: .
      - run:
          name: Disable jekyll builds
          command: touch _site/.nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@3.0.0
            git config user.email "sambuccid@gmail.com"
            git config user.name "sambuccid"
      - add_ssh_keys: #try to upload to github using this key
          fingerprints:
            - "93:fe:cf:1c:ff:65:88:35:0e:4b:d4:9c:4e:5a:9c:43"
      - run:
          #deploy all the files inside the _site folder
          name: Deploy docs to the gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Generate Website" --dist _site
            
workflows:
  say-hello-workflow:
    jobs:
      - docs-build:
          filters:
            branches:
              only: main
      - docs-deploy:
          requires:
            - docs-build
          filters:
            branches:
              only: main
